import BackgroundGrid from "@/components/BackgroundGrid";
import "./globals.css";
import { Space_Grotesk } from "next/font/google";

const space_grotesk = Space_Grotesk({
  subsets: ["latin", "latin-ext"],
  variable: "--font-space-grotesk",
});

export const metadata = {
  title: "SquareLogic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={space_grotesk.variable}>
        <BackgroundGrid />
        {children}
      </body>
    </html>
  );
}
